### ISSUE TITLE
Using stubbed collections for publication tests

### ISSUE THREAD

**Issue by ebbe-brandstrup** [hwillson/meteor-stub-collections#14] opened 2017-01-24 07:53 UTC
Hi,

I'm trying to use the [johanbrook:meteor-publication-collector](https://github.com/johanbrook/meteor-publication-collector) package for publication tests. I would like to use stubbed collections to have the tests run quicker.

The stacktrace of the error I get is:

`Can't publish a cursor from a collection without a name. at [object Object].LocalCollection.Cursor._publishCursor (packages/minimongo.js:265:11) at packages/johanbrook:publication-collector/publication-collector.js:49:20 at Array.map (native) at PublicationCollector.collect (packages/johanbrook:publication-collector/publication-collector.js:44:47)`

It seems to me that the error occurs because this package creates an in-memory (minimongo) collection to replace the real collection by creating a new Meteor collection without a name (null).

I am hoping you have some insight to share?

Thanks!

**Comment by ebbe-brandstrup** [comment] 2017-01-25 09:33
Heads up - the closed issue in the johanbrook:meteor-publication-collector package where I mentioned this issue in did not resolve my problem.

**Comment by hwillson** [comment] 2017-01-25 10:46
Hi @ebbe-brandstrup - thanks for reporting this. Any chance you could put together a small (runnable) repro showing the exact problem? I'll then use that repro to troubleshoot and fix the issue (I'm a bit swamped right now, so providing a runnable repro would definitely help get a fix for this in faster). Also - I love PR's if you're interested in addressing this issue yourself. Thanks again!

**Comment by hwillson** [comment] 2017-11-23 15:30
I'll close this for now, but if you're able to supply a small, runnable reproduction that demonstrates this, I'll take a look. Thanks!

**Closed by hwillson** 2017-11-23 15:30 UTC
Labels: needs-reproduction

**Comment by coagmano** [comment] 2018-03-23 03:12
I've just run into this issue as well. I was unable to make a simple reproduction, but was able to make a fix.

I've added a PR with that fix in #27

**Comment by hwillson** [comment] 2018-03-23 11:57
Thanks @coagmano - I've merged #27 and published `hwillson:stub-collections` version 1.0.7. Let me know if you notice any issues. Thanks again!

**Comment by coagmano** [comment] 2018-03-26 00:18
just realised that this is more likely to break tests that didn't have this issue before because the `collections` object returned from `PublicationCollector` will have the randomised names, where previously folks could just reference the original collection's name.

Working on a better solution that should also fix #24

**Comment by coagmano** [comment] 2018-03-26 02:17
Okay opened a new PR with the changes. Sorry for the mixup!

**Comment by hwillson** [comment] 2018-03-26 11:13
No problem @coagmano - thanks for the fix. Published as `1.0.8`.
